# Generated by Django 4.1.2 on 2022-10-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Post title'),
        ),
    ]
