# Generated by Django 4.1.2 on 2022-10-30 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(default='0.0.0.0', max_length=250, verbose_name='IP address')),
                ('path', models.CharField(blank=True, max_length=250, null=True, verbose_name='Requested URL')),
                ('user_agent', models.CharField(blank=True, max_length=250, null=True, verbose_name="Client's user agent")),
                ('request_method', models.CharField(max_length=10, verbose_name='Request method')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Request datetime')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
